# Generated by Django 5.2.12 on 2026-03-29 11:37

import django.core.validators
import django.db.models.deletion
import torneo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pareja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('jugador1', models.CharField(max_length=100, verbose_name='Jugador 1')),
                ('jugador2', models.CharField(max_length=100, verbose_name='Jugador 2')),
                ('token', models.CharField(default=torneo.models.generar_token, editable=False, max_length=20, unique=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'parejas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ronda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('fase', models.CharField(choices=[('clasificatoria', 'Clasificatoria'), ('octavos', 'Octavos de final'), ('cuartos', 'Cuartos de final'), ('semifinal', 'Semifinal'), ('tercer_puesto', 'Tercer puesto'), ('final', 'Final')], default='clasificatoria', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En curso'), ('completada', 'Completada')], default='pendiente', max_length=20)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_limite', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En curso'), ('finalizada', 'Finalizada')], default='pendiente', max_length=20)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('ganador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidas_ganadas', to='torneo.pareja')),
                ('pareja_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_como_1', to='torneo.pareja')),
                ('pareja_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_como_2', to='torneo.pareja')),
                ('ronda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='torneo.ronda')),
            ],
            options={
                'verbose_name_plural': 'partidas',
            },
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('piedras_1', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(40)], verbose_name='Piedras pareja 1')),
                ('piedras_2', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(40)], verbose_name='Piedras pareja 2')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de confirmación'), ('confirmado', 'Confirmado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('timestamp_subida', models.DateTimeField(auto_now_add=True)),
                ('timestamp_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('ganador_juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juegos_ganados', to='torneo.pareja')),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juegos_subidos', to='torneo.pareja')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juegos', to='torneo.partida')),
            ],
            options={
                'ordering': ['numero'],
                'unique_together': {('partida', 'numero')},
            },
        ),
    ]
