# Generated by Django 5.2.12 on 2026-03-31 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0002_partida_inicio_solicitado_por'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='pareja',
            options={'ordering': ['grupo__nombre', 'nombre'], 'verbose_name_plural': 'parejas'},
        ),
        migrations.AddField(
            model_name='pareja',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parejas', to='torneo.grupo'),
        ),
        migrations.AddField(
            model_name='partida',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidas', to='torneo.grupo'),
        ),
    ]
