# Generated by Django 5.2.12 on 2026-03-31 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0003_grupo_alter_pareja_options_pareja_grupo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='es_amistoso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partida',
            name='juegos_para_ganar',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='partida',
            name='piedras_objetivo',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='partida',
            name='ronda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='torneo.ronda'),
        ),
        migrations.AlterField(
            model_name='ronda',
            name='fase',
            field=models.CharField(choices=[('clasificatoria', 'Clasificatoria'), ('octavos', 'Octavos de final'), ('cuartos', 'Cuartos de final'), ('semifinal', 'Semifinal'), ('tercer_puesto', 'Tercer puesto'), ('final', 'Final'), ('amistoso', 'Amistoso')], default='clasificatoria', max_length=20),
        ),
    ]
