# Generated by Django 5.2.12 on 2026-04-01 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0004_partida_es_amistoso_partida_juegos_para_ganar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pareja',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Teléfono (WhatsApp)'),
        ),
    ]
